name: Bootstrap Jekyll
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

baseurl: /
github_repo: 
production_url:
url: http://yourdomain.com
default_feature_image:

title: Add title here
tagline: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium id nam commodi distinctio nihil asperiores dolores.
admin_email: seth@coelen.co
admin_namae: First Last


timezone: America/New_York
excerpt_separator: <!--more-->
exclude: ["node_modules", "gulpfile.js", "package.json"]

destination: docs


google_analytics_track_id: UA-69335315-1

#Social Media
twitter_username: yourusername
facebook_username: yourusername
org_instagram_username: yourusername

publish: true
